#include "contract_tools.h" 

const char* expected_strings[] = {
    "Success",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "No such device or address",
    "Argument list too long",
    "Exec format error",
    "Bad file descriptor",
    "No child processes",
    "Resource unavailable, try again",
    "Out of memory",
    "Permission denied",
    "Bad address",
    "Device or resource busy",
    "File exists",
    "Cross-device link",
    "No such device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many files open in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Numerical argument out of domain",
    "Result too large",
    "Resource deadlock would occur",
    "File name too long",
    "Directory not empty",
    "Too many levels of symbolic links",
    "Identifier removed",
    "Timer expired",
    "Link has been severed",
    "Protocol error",
    "Value too large to be stored in data type",
    "No locks available",
    "Illegal byte sequence",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not supported",
    "Operation not supported",
    "Network is down",
    "Network is unreachable",
    "Connection timed out",
    "No route to host",
    "Connection already in progress",
    "Operation in progress",
    "Stale file handle",
    "Operation canceled",
    "Previous owner died",
    "State not recoverable"
};

const int errnos[] = {
    0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
    10,  11,  12,  13,  14,  16,  17,  18,  19,  20,
    21,  22,  23,  24,  25,  26,  27,  30,  31,  32,
    33,  34,  35,  36,  39,  40,  43,  62,  67,  71,
    75,  77,  84,  90,  91,  93,  95, 100, 101, 110,
    113, 114, 115, 116, 125, 130, 131
};

void validate_error_strings(void) {
    printf("/*\n");
    printf(" * AUTO-GENERATED errno_to_msg — DO NOT EDIT\n");
    printf(" * Generated by walking error_strings blob\n");
    printf(" */\n");

    printf("static const char* const errno_to_msg[132] = {\n");

    const char* p = error_strings;  // Now from contract_errors.c
    int offset = 0;
    int n = sizeof(expected_strings) / sizeof(expected_strings[0]);

    for (int i = 0; i < n; i++) {
        const char* expected = expected_strings[i];
        int err = expected_errnos[i];

        // Ensure we're at correct string
        while (offset < (int)sizeof(error_strings) && p != error_strings + offset) {
            offset++;
            p = error_strings + offset;
        }

        if (strcmp(p, expected) != 0) {
            printf("/* ERROR: Expected \"%s\", found \"%s\" at offset %d */\n",
                   expected, p, offset);
        }

        printf("    [%3d] = error_strings + %d,  // \"%s\"\n",
               err, offset, expected);

        offset += strlen(p) + 1;
        p = error_strings + offset;
    }

    printf("};\n");
}
